---
title: "Figure for restaurant"
author: "Te-Hsuan Huang"
date: "2025-10-27"
output:
    html_document:
    toc: true
    toc_float: true
---

# Package
```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

# Input the variable
```{r}
data("rest_inspec")

rest_korea=
rest_inspec |> 
  filter(
    !is.na(score),
    latitude != 0,
    boro == "Manhattan",
    cuisine_description == "Korean")
```

# Scatter plot
```{r}
rest_korea |>
  mutate(text_label = str_c("Score:", score, "\nGrade: ", grade)) |> 
  plot_ly(
    x = ~latitude, y = ~longitude, type = "scatter", mode = "markers",
    color = ~grade, text = ~text_label, alpha = 0.5)
```

# Boxplot
```{r}
rest_korea |> 
  mutate(street = fct_reorder(street, score)) |> 
  plot_ly(y = ~score, color = ~street, type = "box", colors = "viridis")
```

# Barchart
```{r}
rest_korea |> 
  count(street) |> 
  mutate(street = fct_reorder(street, n)) |> 
  plot_ly(x = ~street, y = ~n, color = ~street, type = "bar", colors = "viridis")
```

